export const ACTION_TYPES = {
  UPDATE_VALUE: 'UPDATE_VALUE',
  CORRECT_ANSWER: 'CORRECT_ANSWER',
  WRONG_ANSWER: 'WRONG_ANSWER',
  TIME_TICK: 'TIME_TICK',
  NEW_ROUND: 'NEW_ROUND',
  SCORE_ACTIVE_FALSE: 'SCORE_ACTIVE_FALSE',
} as const;
